POST http://localhost:3000/api/weigh
Content-Type: application/json

{
    "id": "5e742e32089beb0738af4bac",
    "price": 35.5, 
    "qty": 54
}


###
POST http://localhost:3000/api/add
Content-Type: application/json

{
    "item":{
        "name": "Item 100",
        "description": "Descripcion de item 1",
        "status": "active",
        "price": 158.00,
        "qty": 4,
        "oldPrice": 0
    }
}

###
GET http://localhost:3000/api
Content-Type: application/json

###
GET http://localhost:3000/api/item/5e742e32089beb0738af4bac
Content-Type: application/json

###
GET http://localhost:3000/api/item/history/5e742e32089beb0738af4bac
Content-Type: application/json